### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by mmucklo** [Art4/json-api-client#29]
Any chance I could persuade you to change the license?

GPL for a library seems a bit heavy handed as by merely using it you'll potentially poison your code base to be forced to be GPL (vs. LGPL which is more amenable for library code)...

**Comment by Art4** [comment]
GPL only affects you if you want to distribute the code, not by using it. I've chosen the license with this in mind.

**Comment by mmucklo** [comment]
Although now your code base becomes legally GPL, like it or not (although
IANAL).

I wonder what happens if an employee knowing this then leaves a company and
puts a legal demand for you to release the GPL code that they are using
(knowing that the whole code base is now GPL due to this package's license).

On May 5, 2016, at 11:07 AM, Artur Weigandt <notifications@github.com>
wrote:

GPL only affects you if you want to distribute the code, not by using it.
I've chosen the license with this in mind.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Art4/json-api-client/issues/29#issuecomment-217228941>

**Comment by Art4** [comment]
> Although now your code base becomes legally GPL, like it or not (although IANAL).
>
> I wonder what happens if an employee knowing this then leaves a company and puts a legal demand for you to release the GPL code that they are using (knowing that the whole code base is now GPL due to this package's license).

I think you're confusing [GPL with AGPL](https://stackoverflow.com/a/2127313). GPL allows you to use and modify the code. Use it on your server, build a (probably paid) service around it. It is free software for your use.

But if you want to distribute the code, for example as an derivative or as part of a bigger software, I'm asking you to give your users the same rights to use and modify the code as I gave to you. Please don't lock this code inside a proprietary software.

I'm not an employee at a software company and I've build this library in my free time to create something that wasn't there before. I've made the code open source so that others can benefit from it as I benefit from other free software.

 IANAL too and I have no interest to sue anybody. But if the license does not coincide with your interests just don't use the library.

By the way: This isn't the right place to discuss this "holy war" potential topic. If you wish to discuss further please come into this gitter chat I've created right now: https://gitter.im/Art4/json-api-client
Thank you.
