### ISSUE TITLE
Invalid JSONAPI data when attributes has a key as "type"

### ISSUE THREAD

**Issue by hackerboydotcom** [Art4/json-api-client#44]
$string = '{"data": {"type": "options","attributes": {"base_product_id": 1,"type": "test"}}}';
var_dump(Parse::isValidRequestString($string));

// Result will be bool(false);
// But if I remove the attribute "type", it'll be bool(true)

**Comment by Art4** [comment]
Hey and thank you for this issue.

Due to the JSON:API spec the attributes `attributes` and `relationships` are called a `field`. This `fields` MUST share a common namespace with each other and with `type` and `id`, so `type` and `id` aren't allowed in `attributes` or `relationships`.

To quote the spec: https://jsonapi.org/format/1.0/#document-resource-object-fields
(bold parts from me)

> Fields
>
> A resource object’s attributes and its relationships are collectively called its “fields”.
> 
> Fields for a resource object MUST share a common namespace with each other and with type and id. In other words, a resource can not have an attribute and relationship with the same name, **nor can it have an attribute or relationship named type** or id.

**Comment by hackerboydotcom** [comment]
Oh, my bad, thank you for the quote

**Comment by Art4** [comment]
You're welcome.
