### ISSUE TITLE
Validator returns true when type or id is integer

### ISSUE THREAD

**Issue by hackerboydotcom** [Art4/json-api-client#47]
Considering this document:
```
{
    "data": {
        "type": "posts",
        "id": 1,
        "attributes": {
            "title": "Post 1 title",
            "content": "Post 1 content"
        }
   }
}
```

The validator will return `true` but it should be `false` because type of ID must be string (Reference: https://jsonapi.org/format/#document-resource-object-identification)

**Comment by hackerboydotcom** [comment]
Hello? Are you up?

**Comment by Art4** [comment]
Hey :wave: I was on vacation and couldn't response earlier. I'm looking into the issue and it is really clear that `id` should be a string. But I'm not sure why I not implemented it strict enough. :confused:

**Comment by Art4** [comment]
Following semantic versioning we can introduce breaking changes while releasing 0.11, because we are on major version zero, see https://semver.org/spec/v2.0.0.html#spec-item-4
One could also arguing that this should be a bug fix (what leads to 0.10.1) because not following the spec strictly is a bug that simply should be fixed. But you are also right that this may crash some apps.

At the moment the parser internally converts a number (of float, boolean, etc) into a string instead of throwing an error, see https://github.com/Art4/json-api-client/blob/0.10/src/V1/ResourceIdentifier.php#L63

My recommendation is to add a deprecation message if `type` or `id` isn't a string and release that as version 0.10.1. In version 1.0 the fields **must** be strings or the parser will throw an Exception.

> and another ErrorCollectionManager for listing all the mistakes in a document.

I would recommend this feature for version 1.1

**Comment by hackerboydotcom** [comment]
Yea, sounds good. I'll take some time to make a PR for that new feature bro 👍

**Comment by Art4** [comment]
Thanks. And I'm working on release 0.10.1 and fixing the master branch.

**Comment by Art4** [comment]
Release 0.10.1 is out, master branch is fixed. Thank you for pointing this out. 👍
